name: Examen Final

on:
  push:
    branches: [main,feature-*,test-pipeline]
  pull_request:
    branches: [main,feature/*]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    # clonar repositorio
    - name: Clonar repo
      uses: actions/checkout@v4

    # configurar Python
    - name: configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # instalar dependencias
    - name: instalar dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # ejecutar flake8
    - name: Run flake8
      run: |
        flake8
    - name: Run Tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
    
    # simular publicacion imagen docker en un registry local
    - name: simular publicacion imagen Docker
      run: |
        echo "Simulando publicacion de imagen Docker en un registry local"
        echo "docker build -t examen-final:latest ."
        echo "imagen Docker examen-final:latest creada"